DATASET_TRAIN:
  PATH: "/home/andrei/Documents/licenta/attributes_train/train_df.pkl"

DATASET_VALID:
  PATH: "/home/andrei/Documents/licenta/attributes_train/val_df.pkl"

TRAIN_SETUP:
  DEVICES: [0]
  WORKERS: 1
  BATCH_SIZE: 16
  EPOCHS: 300
  ITERS_PER_EPOCH: 10000
  SAVE_FREQ: 1
  OPTIMIZER: "adam"
  LEARNING_RATE: 0.001
  WEIGHT_DECAY: 0.0
  PRECISION: "mixed"

MODEL:
  PRETRAINED: "weights/pretrained/ffhq-256.pt"
  SIZE: 256
  TRUNCATION: 0.7
  TRUNCATION_MEAN: 4096
  CHANNEL_MULTIPLIER: 2
  LATENT: 512
  N_MLP: 8
  N_CLASSES: 19