DATASET_INFERENCE:
  SAVE_PATH: "/home/andrei/Documents/licenta/attributes_train_overfit/attributes_df.pkl"
  SAMPLES: 200
  BATCH_SIZE: 1

MODEL:
  PRETRAINED: "weights/pretrained/ffhq-256.pt"
  SIZE: 256
  TRUNCATION: 1.0
  TRUNCATION_MEAN: 4096
  CHANNEL_MULTIPLIER: 2
  LATENT: 512
  N_MLP: 8
  N_CLASSES: 19