DATASET_INFERENCE:
  OUTPUT_DIR: "/home/andrei/Documents/licenta/face_seg_dataset2"
  SAMPLES: 200

MODEL:
  PRETRAINED: "weights/pretrained/ffhq-256.pt"
  SIZE: 256
  TRUNCATION: 0.7
  TRUNCATION_MEAN: 4096
  CHANNEL_MULTIPLIER: 2
  LATENT: 512
  N_MLP: 8
  N_CLASSES: 19